# -*- coding: utf-8 -*-
{
    "name": "IPAI Finance PPM",
    "summary": "Finance Project Portfolio Management (Notion Parity).",
    "version": "18.0.1.1.0",
    "category": "Accounting/Finance",
    "author": "InsightPulseAI",
    "website": "https://insightpulseai.net",
    "license": "AGPL-3",
    "depends": [
        "base",
        "mail",
        "project",
    ],
    "data": [
        "security/ir.model.access.csv",
        "data/finance_person_directory.xml",
        "data/finance_logframe_seed.xml",
        "data/finance_project_data.xml",
        "data/bir_schedule_seed.xml",
        "data/finance_bir_schedule_seed.xml",
        "data/finance_bir_schedule_2026_full.xml",
        "data/finance_cron.xml",
        "data/finance_alert_cron.xml",
        "views/finance_person_views.xml",
        "views/finance_task_views.xml",
        "views/finance_task_extensions.xml",
        "views/finance_project_views.xml",
        "views/bir_schedule_views.xml",
        "views/ppm_dashboard_views.xml",
        "views/ppm_dashboard_template.xml",
        "views/menus.xml",
    ],
    "installable": True,
    "application": True,
}
